### ISSUE TITLE
Kotlin multiplatform not supported

### ISSUE THREAD

**Issue by tjerkw** [razvn/jacoco-to-cobertura-gradle-plugin#6]
I'm using this in a shared multiplatform projects,
where the sourcesets are `commonMain`, `jvmMain`, `androidMain`, `jsMain`

How can i set the sourceset

Caused by: org.gradle.api.UnknownDomainObjectException: SourceSet with name 'main' not found.
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:504)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:333)
        at net.razvan.JacocoToCoberturaPlugin.sourcesRoots(JacocoToCoberturaPlugin.kt:87)
        at net.razvan.JacocoToCoberturaPlugin.convert(JacocoToCoberturaPlugin.kt:38)
        at net.razvan.JacocoToCoberturaPlugin.apply$lambda-1$lambda-0(JacocoToCoberturaPlugin.kt:21)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:770)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:743)
        at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:224)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:207)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:190)
        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:168)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)

**Comment by razvn** [comment]
Hi, thanks for the issue I'll try to look into it to see how to get the sources location in case of a multiplatform project.
I'll keep you posted.

**Comment by razvn** [comment]
Any chance to have a link to a kotlin multiplatform project (with tests) on which I could try a fix ?
